### ISSUE TITLE
can raspberry pi used to do this

### ISSUE THREAD

**Issue by zd200572** [ArjanteMarvelde/uSDR-pico#1]
first, thanks for your work to make the usdr. i wander if i can use my long time unused rpi 3b to make usdr? thanks inadvance!

**Comment by ArjanteMarvelde** [comment]
You mean as a platform for building the UF2 file? I think you can, but I
have never tried it...

**Comment by zd200572** [comment]
Actually l mean to use rpi as a controller instead of P2040. But it seems usdr may not need such high performance cpu.

**Comment by ArjanteMarvelde** [comment]
No, indeed. And the idea of the project is to learn to use this $4 MCU as well as DSP techniques.
