### ISSUE TITLE
v3.0 audio module JP1 errors in schematic?

### ISSUE THREAD

**Issue by fbg2** [ArjanteMarvelde/uSDR-pico#11]
I'm pretty sure the pin numbers and labels are messed up in the schematic for the audio module's JP1 (the connector to CPU-IO). 

Thanks for putting together and sharing this documentation on your fantastic ongoing project.

**Comment by ArjanteMarvelde** [comment]
Yeah, could very well be, this is the only circuit I put on a breadboard. Thanks, I need to sort this out, as well as several other things. 

The HW really is prototype all the way, its just easier to order a PCB than to build it discretely. But anyone who wants to improve: please do!

**Comment by ArjanteMarvelde** [comment]
To be picked up when designing a proper audio PCB.
