### ISSUE TITLE
Problem with waveshare LCD1602 RGB Module

### ISSUE THREAD

**Issue by F1BFU** [ArjanteMarvelde/uSDR-pico#2]
Hi Arjan

I have some problems with this display. I changed lcd.c and lcd.h and I rewrote these files with the instructions given on the Waveshare site and there it works except the special characters. I continue to seek to reinstate your two LCD files.
  I have started welding the plates but I am waiting for components.
However my LCD seems to be the same as yours.
![IMG_20220104_182852](https://user-images.githubusercontent.com/1254586/148101295-8a4a4d42-b756-4e41-aca2-4a4cea929e3b.jpg)
![IMG_20220104_182503](https://user-images.githubusercontent.com/1254586/148101369-01269832-a531-4fdd-bd44-444462141bee.jpg)

Happy new year Arjan
73 QRO
Gilles F1BFU

**Comment by ArjanteMarvelde** [comment]
Hi Gilles,

Happy new year to you as well! I hope we quickly forget 2021...

From the special character it seems you have an older lcd file. I think I solved some issues in the last version.
I your display a Seeed type?

. . . Arjan

**Comment by ArjanteMarvelde** [comment]
Looking at your LCD it seems to be a different one than I use, probably a version with PCF8574 as I2C expander as there are many others like that. Maybe you can insert your (working) code bits into the latest v2.06 lcd.c of the repo?

**Comment by F1BFU** [comment]
Hi Arjan

I tried with the latest version.
it is now just a backlight problem. The data is displayed correctly but very pale.

I will eventually find

73 Gilles F1BFU

**Comment by ArjanteMarvelde** [comment]
Some displays reserve a bit for backlight on/off, but the exact bit may vary between types. 
I'm not sure how to handle all these variations...
