### ISSUE TITLE
What designation do you have written on the processor,

### ISSUE THREAD

**Issue by ra9cua** [ArjanteMarvelde/uSDR-pico#4]
Hello Arjan.
I noticed a difference in performance between processors .
One has the inscription RP2-B1 and the other RP2-B2.
What processor do you have?
When working with the RP2-B1 processor, there are silks after PPM, 
On RP2-B2 they are almost inaudible.

**Comment by ArjanteMarvelde** [comment]
Sergey,
I have only B1 modules. I know that the first HW had a linearity issue in the ADC, so maybe this is causing the noise?
