### ISSUE TITLE
Arduino IDE

### ISSUE THREAD

**Issue by PE1DDA** [ArjanteMarvelde/uSDR-pico#8]
Hello Arjan,

Since the Arduino IDE supports the RP2040 and I'm a bit familiar with that IDE now because of the uSDX projects, I would very much like to try your nice work. I just received my pico W and "blink" to work (with Arduino IDE).
I am a software noob so is there a "tutorial" or description of how to make that work for your software
Your help is very much appreciated.

PE1DDA, Cees
cees.bogaard@gmail.com

**Comment by ArjanteMarvelde** [comment]
Hi Cees,
I will send you a mail
Arjan

**Comment by ArjanteMarvelde** [comment]
PM sent
